### PR TITLE
feat: support history router

### PR DESCRIPTION
**Pull request by amcgee**
The docsify configuration `routerMode: 'history'` breaks the pagination plugin because it assumes links are prefixed with a `#`.  This changes the expected path for `#${path}` only when `routerMode` is set to `hash`

### CODE REVIEW

**Comment by amcgee** [comment]
Ah, just saw that #11 - feel free to close this and merge that one instead since it has an example!

**Comment by amcgee** [comment]
Actually, the implementation is slightly different - this pulls the `routerMode` from the `docsify` config, whereas #11 adds a duplicate `docsify-pagination` config option

**Comment by imyelo** [comment]
#11 is stuck by https://github.com/docsifyjs/docsify/pull/751 for a while, and pulling `routerMode` from `docsify` config is precisely much more ingenious. I'd like to merge this PR if it doesn't affect by https://github.com/docsifyjs/docsify/pull/751 as #11 do.

**Comment by amcgee** [comment]
HI @imyelo sorry for the delay.

I will test this again, I think there may have been an issue with anchor links within pages, but I don't think this requires docsifyjs/docsify#751

**Comment by jcayzac** [comment]
@amcgee @imyelo it's safer to call `vm.router.toURL(path)` instead of hardcoding bahavior like you do here. This PR doesn't support 3rd-party routers, for instance.

**Comment by imyelo** [comment]
> @amcgee @imyelo it's safer to call `vm.router.toURL(path)` instead of hardcoding bahavior like you do here. This PR doesn't support 3rd-party routers, for instance.

Good point! #33 opened with `vm.router.toURL` instead.

**Pull request closed without merging**
